-- Date/Time Functions
SELECT NOW(), CURRENT_DATE(), CURRENT_TIME(), CURRENT_TIMESTAMP();
SELECT YEAR(NOW()), MONTH(NOW()), DAY(NOW());
SELECT HOUR(NOW()), MINUTE(NOW()), SECOND(NOW());
SELECT DATE_FORMAT(NOW(), '%Y-%m-%d'), DATE_FORMAT(NOW(), '%H:%i:%s');
SELECT DATEDIFF(NOW(), '2024-01-01'), TIMEDIFF(NOW(), '2024-01-01 00:00:00');
SELECT DATE_ADD(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 MONTH);
SELECT EXTRACT(YEAR FROM NOW()), EXTRACT(MONTH FROM NOW());
