server:
  host: "127.0.0.1"
  http:
    enabled: true
    port: 8888
    tls_enabled: false
  mysql:
    enabled: true
    port: 13306
    version: "8.0.0"
  redis:
    enabled: true
    port: 16379

security:
  auth_enabled: false
  tls_enabled: false

storage:
  data_dir: "./data"